name: Deploy to staging

on:
  push:
    branches:
      - "main"

jobs:
  redeploy_everything:
    name: Deploying everything to the staging cluster
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
          chmod 600 ~/ssh_key

      - name: SSH and deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@13.201.19.72 << 'EOF'
            export PATH=$PATH:/home/ubuntu/.nvm/versions/node/v22.14.0/bin

            cd devops-25/
            git pull
            /home/ubuntu/.nvm/versions/node/v22.14.0/bin/pnpm install
            /home/ubuntu/.nvm/versions/node/v22.14.0/bin/pnpm run build
            /home/ubuntu/.nvm/versions/node/v22.14.0/bin/pm2 restart http-server
            /home/ubuntu/.nvm/versions/node/v22.14.0/bin/pm2 restart ws-server
            /home/ubuntu/.nvm/versions/node/v22.14.0/bin/pm2 restart fe-server
          EOF
