name: Deploy to staging

on:
  push:
    branches:
      - "main"

jobs:
  redeploy_everything:
    name: Deploying everything to the staging cluster
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
          chmod 600 ~/ssh_key

      - name: SSH and deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@13.201.19.72 << 'EOF'
            export PATH=$PATH:/home/ubuntu/.nvm/versions/node/v22.14.0/bin

            cd devops-25/
            git pull

            pnpm install
            pnpm run build

            # Smart start or restart using PM2
            for app in http-server ws-server fe-server
            do
              if pm2 describe $app > /dev/null; then
                echo "Restarting $app..."
                pm2 restart $app
              else
                echo "Starting $app..."
                pm2 start apps/$app/dist/index.js --name $app
              fi
            done

            pm2 save
          EOF
