name: Deploy to staging
on:
    push:
        branches:
            - "main"


jobs:
    redeploy_everything:
        name: Deploying everything to the staging cluster
        runs-on: ubuntu-latest

        steps:
         - run: |
            echo ${{secrets.SSH_PRIVATE_KEY}} &> ~/ssh_key
            
            ssh -i ~/ssh_key ubuntu@13.201.19.72
            cd devops-25/ && git pull
            pnpm install
            pnpm run build
            pm2 restart http-server
            pm2 restart ws-server
            pm2 restart fe-server

